{
 "title": "Tempo GC Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tempo_build_info, cluster)"
    }
   },
   {
    "name": "component",
    "query": "distributor, ingester, compactor, querier, query-frontend"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 0 },
   "repeat": "component",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 0 },
   "repeat": "component",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 0 },
   "repeat": "component",
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 51 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap in use (bytes)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 68 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{cluster=~\"$cluster\",service=\"tempo-tempo-simplest-$component\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}